pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
               sh script: '''
				   echo "I am in build step"
				   chmod +x gradlew
				   ./gradlew build
               '''
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step"
                    ./gradlew test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "I am in Sonarqube scan"
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                echo "Building DockerImage"
                sh "docker build -t webserver -f .infra/docker/Dockerfile ."
	    }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh script: '''
		    docker login -u "abhi870" -p "dockerhubpass"
                    echo "I am Pubishing DockerImage"
		    docker tag webserver:latest abhi870/webserver:latest
                    docker push abhi870/webserver:latest
                ''',
            label: "Publishing Docker Image"
            	}
	}
    }
    post{
    	always{
		deleteDir()
	}
    }
}
